### ISSUE TITLE
Game crashes before fully loading

### ISSUE THREAD

**Issue by xMrWeaselx** [Y0ungSandwich/Mech-and-Magic#181]
[crash-2017-09-13_19.31.55-client.txt](https://github.com/Y0ungSandwich/Mech-and-Magic/files/1301483/crash-2017-09-13_19.31.55-client.txt)

**Comment by xMrWeaselx** [comment]
I have tried reinstalling the mod pack and Java

**Comment by Physicist1616** [comment]
I also have an issue coincident with the 13 September update.  The log does look different, but I'm on Linux, so perhaps whatever broke xMrWeaselx's install broke in a different way for mine.  

I have tried system updates and switching between OpenJDK and Oracle's JREs; no change.

http://paste.atlauncher.com/view/d2a38eb4

**Comment by Physicist1616** [comment]
I have now also tried regenerating my ATLauncher libraries by just killing ATLauncher/Configs and letting it re-download.  No change.

There was a point recently (Feb) where Forge wouldn't finish launching on AMD on Linux unless you disabled the Forge splash.  I tried disabling that again for this issue.  No change.

**Comment by Physicist1616** [comment]
The pack seems to work in MultiMC if I just symlink the mods and config folders to an instance with the same Forge version.

It seems to me that my issue is ATLauncher specific (although I haven't tested other modpacks).

Good luck xMrWeaselx.  Maybe check to see if you can launch the pack in MultiMC, too.

**Comment by xMrWeaselx** [comment]
Thanks man, although my newest problem is having enough time to play any video games haha

**Comment by Y0ungSandwich** [comment]
This is fixed in a dev version. Just testing now.

**Comment by Physicist1616** [comment]
I still get the same error on 1.1.19.  Still having to use MultiMC.

**Comment by xMrWeaselx** [comment]
Whatever he did in that last update, fixed my issue. I appreciate the timeliness Y0ungSandwich and I wish you luck Physicist1616

**Comment by Y0ungSandwich** [comment]
@Physicist1616 I believe I heard around the grape vine a new gfx driver has messed with MC again. Not sure how true it is but it is. Also I don't know much about linux and drivers outside of servers. 

As far as I can tell your log points no fingers at the pack itself.

**Comment by Physicist1616** [comment]
@Y0ungSandwich I'm guessing it's something in how ATLauncher does its libs and such; MultiMC and Vanilla manage libs each on their own and the game runs fine.  Admittedly, I haven't tested a non-MultiMC forge with this mod/config selection, but MultiMC runs it great.  I even open-to-LAN to a Windows player running ATLauncher M&M and they connect and play fine.
